@startuml
start
:Получить данные о продукте;
:Получить рыночные данные;
:Проверить качество данных;

if (Данные пригодны?) then (да)
  :Рассчитать рекомендованную цену;
  :Сформировать объяснение рекомендации;
  :Передать на согласование;
  if (Цена согласована?) then (да)
    :Опубликовать ценовую рекомендацию;
  else (нет)
    :Отправить на корректировку;
  endif
else (нет)
  :Вернуть данные на очистку;
endif

stop
@enduml